### ISSUE TITLE
Problem about Numbers of MMBench

### ISSUE THREAD

**Issue by 1649759610** [open-compass/MMBench#12]
![image](https://github.com/open-compass/MMBench/assets/35913314/38bba51e-45f1-484f-8300-81846a93471b)

This table lists the number of each split.

I download each split, such as MMBench Test(cn), and loaded with the script [here](https://mmbench.opencompass.org.cn/docs), then count the examples. it is 6666, not 1784 listed in the above table.

Can you explain this for me , thanks.

**Comment by mary-0830** [comment]
There is also this problem. Do you know what's going on?

**Comment by kennymckormick** [comment]
Hi, @1649759610 , #Questions indicates the real number of distinct questions in the datasets, while the number of lines in the tsv file also include the CircularEval passes (for example, 4 copy of a single question if it has 4 choices), so the line number is ~4x of the question number.
