### ISSUE TITLE
[BUG] A potential bug on the evaluation server in handling submissions with the same file name but different contents

### ISSUE THREAD

**Issue by MengLcool** [open-compass/MMBench#16]
Thanks for your effort on the great job.

When using the mmbench server to evaluate our predictions, we encountered a potential bug related to handling submissions with the same file name but different contents.

For instance, if we have two files: 'mmb/7b-reimplement_bug.xlsx' for mmb and 'mmbcn/7b-reimplement_bug.xlsx' for mmbcn, and we submit them to the server one by one, the bug occurs.

The procedure is as follows:

1. Submit ‘mmb/7b-reimplement_bug.xlsx’  to server,  and return true result

2. Submit 'mmbcn/7b-reimplement_bug.xlsx' to the server, which has the same file name as the previous 'mmb/7b-reimplement_bug.xlsx' but is for the 'mmbcn' dataset, and return a false result.

3. Rename 'mmbcn/7b-reimplement_bug.xlsx' to 'mmbcn/7b-reimplement_bug_rename.xlsx' (a different name from the previous submission) and return a true result.

4. Rename 'mmbcn/7b-reimplement_bug_rename.xlsx' back to 'mmbcn/7b-reimplement_bug.xlsx' (the same name as the previous submission) and return a false result.

<img width="1433" alt="image" src="https://github.com/open-compass/MMBench/assets/39439083/3b8e9069-d169-4be8-902c-854db40fef8d">

Looking forward to your response!

**Comment by kennymckormick** [comment]
Hi, @MengLcool , thanks for this report, and we will try to reproduce this bug asap.
