### ISSUE TITLE
How to download the entire leaderboard?

### ISSUE THREAD

**Issue by zhimin-z** [open-compass/MMBench#18]
Including all the evaluation results shown on the webpage?

**Comment by YuanLiuuuuuu** [comment]
Sorry for the late reply. Do you want to download all the results on the webpage as one file?

**Comment by zhimin-z** [comment]
> Sorry for the late reply. Do you want to download all the results on the webpage as one file?

Thanks for your reply. Is that possible? I see some other leaderboards provide a button to download the file as csv for individual panels.

**Comment by YuanLiuuuuuu** [comment]
Currently, we do not support such feature, and will have a discussion about the possibility to add it.

**Comment by zhimin-z** [comment]
> Hi, @zhimin-z , we have made the leaderboard downloadable as a single json file. Check the homepage of VLMEvalKit for the download link: https://github.com/open-compass/VLMEvalKit/blob/739915bd3a17de825e90d9106b568166b7d4806e/README.md?plain=1#L16.

This is no longer accessible... @kennymckormick
