### ISSUE TITLE
An error in CCBench file

### ISSUE THREAD

**Issue by schuper** [open-compass/MMBench#20]
![image](https://github.com/open-compass/MMBench/assets/109776374/32ac6d9d-1f4d-4624-a8f7-6e64d7b1de20)
As shown above, the answers is CC. The above situation appears in CCBench which index is 319, 1000319, 2000319 and 3000319. I think it have not been paying attention.

**Comment by kennymckormick** [comment]
Thanks, @schuper , we will fix it in a later update.

**Comment by kennymckormick** [comment]
Hi, @schuper , the problem has been fixed, please adopt the latest VLMEvalKit for evaluation.
