### ISSUE TITLE
Evaluation returns all zeros

### ISSUE THREAD

**Issue by simplelifetime** [open-compass/MMBench#21]
All the evaluation results return all zeros. Evaluation logs show 'CHATGPT api is not working'

**Comment by nicedoctor** [comment]
got the same problem

**Comment by nbasyl** [comment]
Same here, @kennymckormick could you please take a look? I checked the evaluation log, it said chatgpt api is not working which I assume is the problem here ?

**Comment by kennymckormick** [comment]
Hey guys @simplelifetime @nicedoctor @nbasyl , this issue has been solved now. Now the platform can successfully complete the evaluation.

**Comment by Lin-Tianwei** [comment]
从除夕夜到目前为止，我一直试图提交测试，然而返回的结果都是“ChatGPT API is not working”，请问是出了什么问题吗 @kennymckormick

**Comment by kennymckormick** [comment]
> 从除夕夜到目前为止，我一直试图提交测试，然而返回的结果都是“ChatGPT API is not working”，请问是出了什么问题吗 @kennymckormick

Hi, Tianwei,
Our API service is experiencing failure and we may not be able to fix it during the new year holiday. As a temporary solution, you can send your prediction results to opencompass@pjlab.org.cn and we will help you with the evaluation.

**Comment by Isaachhh** [comment]
@kennymckormick I have sent my submissions to the email box and I sincerely request for your help. Thank you so so much!
