### ISSUE TITLE
Where is the report or paper on CCBench?

### ISSUE THREAD

**Issue by zhimin-z** [open-compass/MMBench#22]
I cannot locate any mention of CCBench in the [MMBench](https://arxiv.org/abs/2307.06281) Arxiv paper.

**Comment by zhimin-z** [comment]
Which organization released CCBench?
Still `Shanghai AI Laboratory, Nanyang Technological University, The Chinese University of Hong Kong, National University of Singapore, Zhejiang University`?

**Comment by kennymckormick** [comment]
Hi, @zhimin-z , 
CCBench is released by the same org as MMBench, we will update the technical report to add more detailed about CCBench
