### ISSUE TITLE
How can i download the image?

### ISSUE THREAD

**Issue by SCAUapc** [open-compass/MMBench#23]
in the dataset, i just see the "image" column such as "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGB....." . How can i get the entired image?

**Comment by kennymckormick** [comment]
> i have the same question

Please refer to the README to load and parse the dataset. 

![image](https://github.com/open-compass/MMBench/assets/34324155/b57aae3e-23f4-4d57-8eec-42d99b68a4a3)
