### ISSUE TITLE
Scores of L-3 Abilities on the Leaderboard

### ISSUE THREAD

**Issue by TsuTikgiau** [open-compass/MMBench#24]
Thanks for the nice benchmark. I noticed that the leaderboard provides the overall scores and the L-2 ability scores of the evaluated models. How can we see the detailed L-3 ability scores on the leaderboard? Such information would be helpful to better understand the evaluated models' abilities and limitations. Thank you!

**Comment by kennymckormick** [comment]
Hi, @TsuTikgiau , 
we are going to include this in our `open_vlm_leadarboard`: https://huggingface.co/spaces/opencompass/open_vlm_leaderboard. Stays tuned.

**Comment by kennymckormick** [comment]
Hi, @TsuTikgiau ,
The scores are already included in Open VLM Leaderboard.
