### ISSUE TITLE
Evaluation server return 0 score

### ISSUE THREAD

**Issue by czczup** [open-compass/MMBench#25]
Hello, there seems to be a problem with the evaluation server, both dev and test sets have returned 0 scores in the last few days.

<img width="926" alt="image" src="https://github.com/open-compass/MMBench/assets/23737120/a6a06970-565e-424f-a966-0dcfcb40919f">

**Comment by LinB203** [comment]
same question. 5 days at least.

**Comment by kennymckormick** [comment]
Our evaluation service is temporarily down, please send your prediction files to opencompass@pjlab.org.cn instead.

**Comment by Lin-Tianwei** [comment]
@kennymckormick Hello, I have sent the prediction file to your email. Thank you very much for your help.

**Comment by zodiacg** [comment]
@Lin-Tianwei Hi, have you received your results? How long does it take to evaluate the results currently?

**Comment by kennymckormick** [comment]
Hi, all, 
the evaluation server has already been fixed now.
