### ISSUE TITLE
V1.1 Test 评测

### ISSUE THREAD

**Issue by Sync-yxh** [open-compass/MMBench#32]
请问一下，V1.1 Test集合，评测方式和此前一致吗？官网上传submission.xlsx文件，是内部自动通过index来区分 20231003 版本 和 V1.1 版本吗？

**Comment by Sync-yxh** [comment]
同时想请问下，如何区分 CN 和 EN 区别？ index似乎是一样的。

**Comment by kennymckormick** [comment]
Hi, @Sync-yxh , 
1. 我们通过 index 区分 v1.0 与 v1.1 版本
2. CN 与 EN 的区别在于，CN 的问题，选项为中文，我们会通过脚本检测问题是否为中文，从而区分 CN / EN

**Comment by ZhuGeKongKong** [comment]
那现在提交网站给出的测评结果是v1.1的还是v1.0的？

**Comment by kennymckormick** [comment]
Hi, @ZhuGeKongKong , 
目前提交网站可以同时处理 V1.0 / V1.1 的输入文件，会根据文件的内容匹配到对应的版本

**Comment by ZhuGeKongKong** [comment]
v1.1的测试集从哪里下载呀？官网上给的数据还是1003的我看

**Comment by kennymckormick** [comment]
@ZhuGeKongKong ,
参照 [README](https://github.com/open-compass/MMBench) 描述，推荐使用 VLMEvalKit 进行评测 MMBench：https://github.com/open-compass/VLMEvalKit
指定数据集名称为 MMBench_[DEV/TEST]_[EN/CN]_V11 即可，对于 TEST split，推理完成后，将输出文件提交至评测服务即可
