### ISSUE TITLE
where is the images in dataset?

### ISSUE THREAD

**Issue by ALR-alr** [open-compass/MMBench#33]
where can i download them?

**Comment by ALR-alr** [comment]
I had come across the multimodal dataset where the image url is given. But in this MMBench dataset,  only image path is given. How can I deal with it? LOOKING FORWARD TO YOUR REPLY!

**Comment by kennymckormick** [comment]
Please refer to the README to load and parse the dataset:

![image](https://github.com/open-compass/MMBench/assets/34324155/04445d05-3049-45df-aa86-a647b651b84d)

**Comment by ALR-alr** [comment]
thanks very much for your reply! When I received your reply in the morning, I started to configure the vlmeval environment. In the afternoon, the laboratory server was unexpectedly shut down. Now I have no cuda, so I can't verify it immediately. Will the output here means running the vlmeval package can automatically download pictures ? I see that it outputs a local file path like " 'value': '/root/LMUData/image/MMBench/241,jpg'".

**Comment by ALR-alr** [comment]
> Please refer to the README to load and parse the dataset:
> 
> ![image](https://private-user-images.githubusercontent.com/34324155/340162838-04445d05-3049-45df-aa86-a647b651b84d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDI3NTIsIm5iZiI6MTcxODcwMjQ1MiwicGF0aCI6Ii8zNDMyNDE1NS8zNDAxNjI4MzgtMDQ0NDVkMDUtMzA0OS00NWRmLWFhODYtYTY0N2I2NTFiODRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA5MjA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNjA5OTlmNTljZWFjNTY5M2VlYzA3YjY4MTU0M2ZhMzM4Yjk4NjU0NWE1MjBjOWU1OWM3NjdkNzNmNjY0NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v_fXpU6oXtE3wLkgrs-0UdfFgEDEK6HU4E4RDl8fODU)

Oh I see, it's magical! A string encoded by base_64 can be decoded to a picture!
