### ISSUE TITLE
您好，请问1.1版本更新的具体内容是什么？

### ISSUE THREAD

**Issue by hl0737** [open-compass/MMBench#35]
RT

ReadMe和Commit中均未看见版本更新说明，是更新了数据集嘛？

以及，安装完VlmEval后，在vlmeval.utils目录下没有TSVDataset，导致import error

![image](https://github.com/user-attachments/assets/e0a2d1a9-f969-455c-8b47-252f74e7d44f)

**Comment by kennymckormick** [comment]
Hi, @hl0737 
抱歉，在我们改版 VLMEvalKit 后还未对本 repo 中的 instruction 进行更新，我们将完成更新后通知您

**Comment by kennymckormick** [comment]
Hi, @hl0737 
我们已经更新了相关 instruction。v1.1 相比 v1.0 进行了数据的删减与增补，可以对比我们 arxiv 论文的 v3 与 v4
