### ISSUE TITLE
[dataset] The download link[VLMEvalKit & Legacy] seems to be broken.

### ISSUE THREAD

**Issue by YunfengLiu** [open-compass/MMBench#38]
The links for downloading MMBench are currently unavailable.  Where can I download MMBench v1.1?
<img width="746" alt="image" src="https://github.com/user-attachments/assets/191694ec-366e-417d-a869-aec1f2754c13">

**Comment by kennymckormick** [comment]
Hi, I can successfully download those links, please check if you are using proxy.

For MMBench V1.1, please follow the instruction of VLMEvalKit to perform the evaluation: 
https://github.com/open-compass/VLMEvalKit

**Comment by YunfengLiu** [comment]
OK！Thank You！
