### ISSUE TITLE
mmbench-v1.1

### ISSUE THREAD

**Issue by aoji0606** [open-compass/MMBench#39]

**Comment by aoji0606** [comment]
请问test-en-v1.1和test-cn-v1.1的数据在哪里下载呢

**Comment by kennymckormick** [comment]
Hi, @aoji0606 ,
你可以参照 VLMEvalKit 中的教程对 MMBench-V1.1 进行评估。

**Comment by yanaenen** [comment]
VLMEvalKit里的MMBench-V1.1 数据集的链接下载不了，打开链接显示

`
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<RequestId>670498F94C586D32382A3C13</RequestId>
<HostId>opencompass.openxlab.space</HostId>
<Key>utils/VLMEval/MMBench_V11.tsv</Key>
</Error>
`

**Comment by kennymckormick** [comment]
Hi，@yanaenen, 

MMBench_V11 为内部使用的文件，我们对外是分 dev 和 test 进行 release 的，具体名称请参照 VLMEvalKit 主页：

![image](https://github.com/user-attachments/assets/7d2d7e17-43cb-4831-8be5-82b291f836c1)
