### ISSUE TITLE
Not able to upload .xlsx submission file for MMBench_TEST_EN. Showing upload error.

### ISSUE THREAD

**Issue by rodosingh** [open-compass/MMBench#40]
Even after satisfying the requirements and constraints as mentioned in [Evaluation site](https://mmbench.opencompass.org.cn/mmbench-submission) and shown below in the image, I am not able to upload the `*.xlsx` file.
Can you please look into the issue?

![image](https://github.com/user-attachments/assets/ef64f064-209f-478d-bf20-8c7d25310f41)

**Comment by kennymckormick** [comment]
Hi, @rodosingh , 
The problem has been fixed now.

**Comment by rodosingh** [comment]
Thanks @kennymckormick for solving it. Let me test it.
