### ISSUE TITLE
无法访问https://mmbench.opencompass.org.cn/mmbench-submission 

### ISSUE THREAD

**Issue by Purshow** [open-compass/MMBench#44]
作者您好！我遇到了无法访问https://mmbench.opencompass.org.cn/mmbench-submission 的问题

**Comment by kennymckormick** [comment]
Hi，我可以访问这个链接，请检查您的 VPN 是否关闭

另外，评测服务需要登陆后才可使用

**Comment by Purshow** [comment]
十分抱歉给您造成了麻烦，我现在发现我可以访问了，感谢您的回复！
