### ISSUE TITLE
测评很慢，测了一晚上都没出结果...

### ISSUE THREAD

**Issue by SihengLi99** [open-compass/MMBench#9]

**Comment by kennymckormick** [comment]
Hi, @SihengLi99 , 
That may due to a temporary run out of API quota. We will notify you once we have enough quota for the evaluation.

**Comment by kennymckormick** [comment]
Hi, @SihengLi99 , the evaluation service is OK now. Besides, we have supported a mechanism to return the accuracy under **exact matching** when we ran out of API quota (a message will also be returned in the log).
